# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Black Code Formatter
      # You may pin to the exact commit or the version.
      # uses: lgeiger/black-action@4379f39aa4b6a3bb1cceb46a7665b9c26647d82d
      uses: lgeiger/black-action@v1.0.1
      run: | 
        black . --check
    - name: Test with pytest
      run: |
        pytest
